=== KKrisztofer/TRNA8A_XMLGyak/XMLTaskTRNA8A/XMLSchemaTRNA8A.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="webshop">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vasarlo" type="vasarloTipus" maxOccurs="unbounded"/>
                <xs:element name="termek" type="termekTipus" maxOccurs="unbounded"/>
                <xs:element name="futarceg" type="futarcegTipus" maxOccurs="unbounded"/>
                <xs:element name="nyilvantartas" type="nyilvantartasTipus" maxOccurs="unbounded"/>
                <xs:element name="rendeles" type="rendelesTipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <!-- Elsődleges kulcsok -->
        <xs:key name="vasarloKulcs">
            <xs:selector xpath="vasarlo"/>
            <xs:field xpath="@vid"/>
        </xs:key>

        <xs:key name="termekKulcs">
            <xs:selector xpath="termek"/>
            <xs:field xpath="@tid"/>
        </xs:key>

        <xs:key name="futarcegKulcs">
            <xs:selector xpath="futarceg"/>
            <xs:field xpath="@fid"/>
        </xs:key>

        <xs:key name="rendelesKulcs">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@rid"/>
        </xs:key>

        <!-- Idegen kulcsok -->
        <xs:keyref refer="vasarloKulcs" name="rendelesVasarloIdegenKulcs">
            <xs:selector xpath="rendeles"/>
            <xs:field xpath="@vid_f"/>
        </xs:keyref>

        <xs:keyref refer="termekKulcs" name="raktarTermekIdegenKulcs">
            <xs:selector xpath="nyilvantartas"/>
            <xs:field xpath="@tid_f"/>
        </xs:keyref>

        <xs:keyref refer="futarcegKulcs" name="rendelesFutarcegIdegenKulcs">
            <xs:selector xpath="futar"/>
            <xs:field xpath="@fid_f"/>
        </xs:keyref>

    </xs:element>

    <!-- Saját típusok -->
    <xs:complexType name="vasarloTipus">
        <xs:sequence>
            <xs:element name="vezeteknev" type="xs:string"/>
            <xs:element name="keresztnev" type="xs:string"/>
            <xs:element name="cim">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="varos" type="xs:string"/>
                        <xs:element name="utca" type="xs:string"/>
                        <xs:element name="hazszam" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="telefonszam" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="vid" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="termekTipus">
        <xs:sequence>
            <xs:element name="elnevezes" type="xs:string"/>
            <xs:element name="leiras" type="xs:string" minOccurs="0"/>
            <xs:element name="ar" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="tid" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="futarcegTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="cim" type="xs:string"/>
            <xs:element name="szallitasiido" type="xs:string"/>
            <xs:element name="ar" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="fid" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="nyilvantartasTipus">
        <xs:sequence>
            <xs:element name="mennyiseg" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="tid_f" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="rendelesTipus">
        <xs:sequence>
            <xs:element name="datum">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ev" type="xs:string"/>
                        <xs:element name="honap" type="xs:string"/>
                        <xs:element name="nap" type="xs:string"/>
                        <xs:element name="ora" type="xs:string"/>
                        <xs:element name="perc" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="tartalom">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="arucikk" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="tid_f" type="xs:string"/>
                                    <xs:element name="mennyiseg" type="xs:integer"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="vegosszeg" type="xs:integer"/>
            <xs:element name="futar">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="fid_f" type="xs:string"/>
                        <xs:element name="felvetel" type="xs:string"/>
                        <xs:element name="kezbesites" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="rid" type="xs:string" use="required"/>
        <xs:attribute name="vid_f" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== KKrisztofer/TRNA8A_XMLGyak/XMLTaskTRNA8A/DOMParseTRNA8A/XMLTRNA8A.xml
<?xml version="1.0" encoding="UTF-8"?>
<webshop xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaTRNA8A.xsd">

    <!-- Vásárlók -->
    <vasarlo vid="v001">
        <vezeteknev>Kerekes</vezeteknev>
        <keresztnev>Krisztofer</keresztnev>
        <cim>
            <varos>Nyékládháza</varos>
            <utca>Balassi Bálint</utca>
            <hazszam>37</hazszam>
        </cim>
        <telefonszam>06706102436</telefonszam>
    </vasarlo>

    <!-- Termékek -->
    <termek tid="t001">
        <elnevezes>Samsung UE43TU7022 TV</elnevezes>
        <leiras>Merülj el a képben a szélesebb színskálával! A Crystal Display biztosítja az optimalizált színkifejezést, így minden részletet láthatsz.</leiras>
        <ar>129899</ar>
    </termek>
    <termek tid="t002">
        <elnevezes>Apple iPhone 13 128GB Mobiltelefon</elnevezes>
        <leiras>Az ultraszéles látószögű kamera közvetlen közelről is nagy látóteret ad, hogy hátralépés nélkül is többet belefoglalhass a látványból a képbe.</leiras>
        <ar>312970</ar>
    </termek>
    <termek tid="t003">
        <elnevezes>Samsung Galaxy A52s 5G 128GB</elnevezes>
        <leiras>A következő generációs mobiladat-hálózaton az 5G sebesség megváltoztatja a tapasztalatok és a tartalom megosztásának módját, a szuper gördülékeny játéktól és streamingtől kezdve az ultragyors megosztásig és letöltésig. Válts Samsung Galaxy A52s 5G-re és tapasztald meg a valódi gyorsaságot!</leiras>
        <ar>136990</ar>
    </termek>
    <termek tid="t004">
        <elnevezes>ASUS X515EA-BQ1187 Notebook</elnevezes>
        <ar>184990</ar>
    </termek>
    <termek tid="t005">
        <elnevezes>Samsung Galaxy Watch 5 40mm</elnevezes>
        <leiras>Kövesd nyomod egészséged még éjszaka is!</leiras>
        <ar>88190</ar>
    </termek>

    <!-- Futárcégek -->
    <futarceg fid="f01">
        <nev>FOXPOST</nev>
        <cim>1097 Budapest, Könyves Kálmán krt. 12-14</cim>
        <szallitasiido>2 nap</szallitasiido>
        <ar>1499</ar>
    </futarceg>
    <futarceg fid="f02">
        <nev>GLS</nev>
        <cim>Budapest</cim>
        <szallitasiido>3 nap</szallitasiido>
        <ar>1799</ar>
    </futarceg>
    <futarceg fid="f03">
        <nev>Packeta</nev>
        <cim>Budapest Ezred utca 2</cim>
        <szallitasiido>4 nap</szallitasiido>
        <ar>2000</ar>
    </futarceg>

    <!-- Raktár -->
    <nyilvantartas tid_f="t001">
        <mennyiseg>15</mennyiseg>
    </nyilvantartas>
    <nyilvantartas tid_f="t002">
        <mennyiseg>6</mennyiseg>
    </nyilvantartas>
    <nyilvantartas tid_f="t003">
        <mennyiseg>32</mennyiseg>
    </nyilvantartas>
    <nyilvantartas tid_f="t004">
        <mennyiseg>24</mennyiseg>
    </nyilvantartas>
    <nyilvantartas tid_f="t005">
        <mennyiseg>13</mennyiseg>
    </nyilvantartas>

    <!-- Rendelések -->
    <rendeles rid="r001" vid_f="v001">
        <datum>
            <ev>2022</ev>
            <honap>11</honap>
            <nap>03</nap>
            <ora>14</ora>
            <perc>32</perc>
        </datum>
        <tartalom>
            <arucikk>
                <tid_f>t002</tid_f>
                <mennyiseg>1</mennyiseg>
            </arucikk>
            <arucikk>
                <tid_f>t003</tid_f>
                <mennyiseg>2</mennyiseg>
            </arucikk>
        </tartalom>
        <vegosszeg>314469</vegosszeg>
        <futar>
            <fid_f>f01</fid_f>
            <felvetel>2022-11-04</felvetel>
            <kezbesites>2022-11-05</kezbesites>
        </futar>
    </rendeles>
</webshop>
